// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeKeeper.Data;

#nullable disable

namespace TimeKeeper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TimeKeeper.Models.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            id = 1,
                            address = "A demo company address",
                            name = "D.E.M.O. Company"
                        });
                });

            modelBuilder.Entity("TimeKeeper.Models.Month", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("grade")
                        .HasColumnType("float");

                    b.Property<double>("payPerHour")
                        .HasColumnType("float");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<double>("workHours")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Months");

                    b.HasData(
                        new
                        {
                            id = 1,
                            date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            grade = 5.0,
                            payPerHour = 16.489999999999998,
                            salary = 1752.83203125,
                            userId = 1,
                            workHours = 106.29666666666662
                        },
                        new
                        {
                            id = 2,
                            date = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            grade = 5.0,
                            payPerHour = 16.489999999999998,
                            salary = 4179.830078125,
                            userId = 1,
                            workHours = 253.47666666666677
                        },
                        new
                        {
                            id = 3,
                            date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            grade = 5.0,
                            payPerHour = 16.489999999999998,
                            salary = 3775.33056640625,
                            userId = 1,
                            workHours = 228.94666666666674
                        },
                        new
                        {
                            id = 4,
                            date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            grade = 5.0,
                            payPerHour = 16.489999999999998,
                            salary = 4179.830078125,
                            userId = 1,
                            workHours = 253.47666666666677
                        });
                });

            modelBuilder.Entity("TimeKeeper.Models.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("companyId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            id = 1,
                            companyId = 1,
                            description = "Official project of the demo company",
                            name = "A Demo Company's demo project"
                        });
                });

            modelBuilder.Entity("TimeKeeper.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("companyId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("grade")
                        .HasColumnType("float");

                    b.Property<string>("guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("payPerHour")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            companyId = 1,
                            email = "demo@mail.com",
                            firstName = "Demo",
                            grade = 5.0,
                            guid = "9de8ec34-e8ec-45f5-af13-877256e6fb95",
                            isAdmin = true,
                            lastName = "Account",
                            password = "80EA7B3C979BF51045EA9EB2FAABBBFC858BECABA5A653EC9E06965DF5FA95843045C25BFD66E63F202FA5E04A9CF7C1F2889F769C0AEEB2458D3F373D1BE439",
                            payPerHour = 16.489999999999998
                        });
                });

            modelBuilder.Entity("TimeKeeper.Models.UserSalt", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("email");

                    b.ToTable("UserSalts");

                    b.HasData(
                        new
                        {
                            email = "demo@mail.com",
                            salt = new byte[] { 76, 21, 201, 90, 10, 67, 184, 0, 230, 125, 191, 193, 4, 83, 66, 74, 110, 198, 237, 92, 28, 181, 15, 231, 47, 56, 55, 77, 245, 188, 7, 41, 59, 7, 158, 72, 86, 100, 9, 108, 228, 219, 74, 165, 157, 245, 117, 229, 50, 89, 57, 158, 126, 51, 249, 168, 172, 221, 240, 81, 210, 73, 143, 176 }
                        });
                });

            modelBuilder.Entity("TimeKeeper.Models.Workday", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("attachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("clockIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("clockOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("grade")
                        .HasColumnType("float");

                    b.Property<int?>("projectId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<double?>("workHours")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Workdays");

                    b.HasData(
                        new
                        {
                            id = 1,
                            clockIn = new DateTime(2023, 4, 1, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 1, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 2,
                            clockIn = new DateTime(2023, 4, 2, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 2, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 3,
                            clockIn = new DateTime(2023, 4, 3, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 3, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 4,
                            clockIn = new DateTime(2023, 4, 4, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 4, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 5,
                            clockIn = new DateTime(2023, 4, 5, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 5, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 6,
                            clockIn = new DateTime(2023, 4, 6, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 6, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 7,
                            clockIn = new DateTime(2023, 4, 7, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 7, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 8,
                            clockIn = new DateTime(2023, 4, 8, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 8, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 9,
                            clockIn = new DateTime(2023, 4, 9, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 9, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 10,
                            clockIn = new DateTime(2023, 4, 10, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 10, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 11,
                            clockIn = new DateTime(2023, 4, 11, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 11, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 12,
                            clockIn = new DateTime(2023, 4, 12, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 12, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 13,
                            clockIn = new DateTime(2023, 4, 13, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 4, 13, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 14,
                            clockIn = new DateTime(2023, 4, 14, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1
                        },
                        new
                        {
                            id = 15,
                            clockIn = new DateTime(2023, 3, 1, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 1, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 16,
                            clockIn = new DateTime(2023, 3, 2, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 2, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 17,
                            clockIn = new DateTime(2023, 3, 3, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 3, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 18,
                            clockIn = new DateTime(2023, 3, 4, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 4, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 19,
                            clockIn = new DateTime(2023, 3, 5, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 5, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 20,
                            clockIn = new DateTime(2023, 3, 6, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 6, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 21,
                            clockIn = new DateTime(2023, 3, 7, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 7, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 22,
                            clockIn = new DateTime(2023, 3, 8, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 8, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 23,
                            clockIn = new DateTime(2023, 3, 9, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 9, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 24,
                            clockIn = new DateTime(2023, 3, 10, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 10, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 25,
                            clockIn = new DateTime(2023, 3, 11, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 11, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 26,
                            clockIn = new DateTime(2023, 3, 12, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 12, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 27,
                            clockIn = new DateTime(2023, 3, 13, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 13, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 28,
                            clockIn = new DateTime(2023, 3, 14, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 14, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 29,
                            clockIn = new DateTime(2023, 3, 15, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 15, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 30,
                            clockIn = new DateTime(2023, 3, 16, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 16, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 31,
                            clockIn = new DateTime(2023, 3, 17, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 17, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 32,
                            clockIn = new DateTime(2023, 3, 18, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 18, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 33,
                            clockIn = new DateTime(2023, 3, 19, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 19, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 34,
                            clockIn = new DateTime(2023, 3, 20, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 20, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 35,
                            clockIn = new DateTime(2023, 3, 21, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 21, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 36,
                            clockIn = new DateTime(2023, 3, 22, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 22, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 37,
                            clockIn = new DateTime(2023, 3, 23, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 23, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 38,
                            clockIn = new DateTime(2023, 3, 24, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 24, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 39,
                            clockIn = new DateTime(2023, 3, 25, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 25, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 40,
                            clockIn = new DateTime(2023, 3, 26, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 26, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 41,
                            clockIn = new DateTime(2023, 3, 27, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 27, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 42,
                            clockIn = new DateTime(2023, 3, 28, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 28, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 43,
                            clockIn = new DateTime(2023, 3, 29, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 29, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 44,
                            clockIn = new DateTime(2023, 3, 30, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 30, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 45,
                            clockIn = new DateTime(2023, 3, 31, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 3, 31, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 46,
                            clockIn = new DateTime(2023, 2, 1, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 1, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 47,
                            clockIn = new DateTime(2023, 2, 2, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 2, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 48,
                            clockIn = new DateTime(2023, 2, 3, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 3, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 49,
                            clockIn = new DateTime(2023, 2, 4, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 4, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 50,
                            clockIn = new DateTime(2023, 2, 5, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 5, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 51,
                            clockIn = new DateTime(2023, 2, 6, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 6, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 52,
                            clockIn = new DateTime(2023, 2, 7, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 7, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 53,
                            clockIn = new DateTime(2023, 2, 8, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 8, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 54,
                            clockIn = new DateTime(2023, 2, 9, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 9, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 55,
                            clockIn = new DateTime(2023, 2, 10, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 10, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 56,
                            clockIn = new DateTime(2023, 2, 11, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 11, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 57,
                            clockIn = new DateTime(2023, 2, 12, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 12, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 58,
                            clockIn = new DateTime(2023, 2, 13, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 13, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 59,
                            clockIn = new DateTime(2023, 2, 14, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 14, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 60,
                            clockIn = new DateTime(2023, 2, 15, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 15, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 61,
                            clockIn = new DateTime(2023, 2, 16, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 16, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 62,
                            clockIn = new DateTime(2023, 2, 17, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 17, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 63,
                            clockIn = new DateTime(2023, 2, 18, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 18, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 64,
                            clockIn = new DateTime(2023, 2, 19, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 19, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 65,
                            clockIn = new DateTime(2023, 2, 20, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 20, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 66,
                            clockIn = new DateTime(2023, 2, 21, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 21, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 67,
                            clockIn = new DateTime(2023, 2, 22, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 22, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 68,
                            clockIn = new DateTime(2023, 2, 23, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 23, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 69,
                            clockIn = new DateTime(2023, 2, 24, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 24, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 70,
                            clockIn = new DateTime(2023, 2, 25, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 25, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 71,
                            clockIn = new DateTime(2023, 2, 26, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 26, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 72,
                            clockIn = new DateTime(2023, 2, 27, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 27, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 73,
                            clockIn = new DateTime(2023, 2, 28, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 2, 28, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 74,
                            clockIn = new DateTime(2023, 1, 1, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 1, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 75,
                            clockIn = new DateTime(2023, 1, 2, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 2, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 76,
                            clockIn = new DateTime(2023, 1, 3, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 3, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 77,
                            clockIn = new DateTime(2023, 1, 4, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 4, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 78,
                            clockIn = new DateTime(2023, 1, 5, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 5, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 79,
                            clockIn = new DateTime(2023, 1, 6, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 6, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 80,
                            clockIn = new DateTime(2023, 1, 7, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 7, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 81,
                            clockIn = new DateTime(2023, 1, 8, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 8, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 82,
                            clockIn = new DateTime(2023, 1, 9, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 9, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 83,
                            clockIn = new DateTime(2023, 1, 10, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 10, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 84,
                            clockIn = new DateTime(2023, 1, 11, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 11, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 85,
                            clockIn = new DateTime(2023, 1, 12, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 12, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 86,
                            clockIn = new DateTime(2023, 1, 13, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 13, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 87,
                            clockIn = new DateTime(2023, 1, 14, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 14, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 88,
                            clockIn = new DateTime(2023, 1, 15, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 15, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 89,
                            clockIn = new DateTime(2023, 1, 16, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 16, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 90,
                            clockIn = new DateTime(2023, 1, 17, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 17, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 91,
                            clockIn = new DateTime(2023, 1, 18, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 18, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 92,
                            clockIn = new DateTime(2023, 1, 19, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 19, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 93,
                            clockIn = new DateTime(2023, 1, 20, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 20, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 94,
                            clockIn = new DateTime(2023, 1, 21, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 21, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 95,
                            clockIn = new DateTime(2023, 1, 22, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 22, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 96,
                            clockIn = new DateTime(2023, 1, 23, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 23, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 97,
                            clockIn = new DateTime(2023, 1, 24, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 24, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 98,
                            clockIn = new DateTime(2023, 1, 25, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 25, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 99,
                            clockIn = new DateTime(2023, 1, 26, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 26, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 100,
                            clockIn = new DateTime(2023, 1, 27, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 27, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 101,
                            clockIn = new DateTime(2023, 1, 28, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 28, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 102,
                            clockIn = new DateTime(2023, 1, 29, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 29, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 103,
                            clockIn = new DateTime(2023, 1, 30, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 30, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        },
                        new
                        {
                            id = 104,
                            clockIn = new DateTime(2023, 1, 31, 8, 50, 37, 0, DateTimeKind.Unspecified),
                            clockOut = new DateTime(2023, 1, 31, 17, 1, 13, 0, DateTimeKind.Unspecified),
                            date = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            description = "Worked on Demo Company's demo project",
                            grade = 5.0,
                            projectId = 1,
                            userId = 1,
                            workHours = 8.1766666666666659
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
